services:

  n8n:
    image: n8nio/n8n:latest
    container_name: nusa-dhipa-n8n
    restart: unless-stopped

    ports:
      - "5678:5678"

    env_file:
      - .env

    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Asia/Jakarta
      - TZ=Asia/Jakarta

    volumes:
      - nusa_dhipa_n8n_data:/home/node/.n8n

volumes:
  nusa_dhipa_n8n_data:
